### ISSUE TITLE
checkbox, type = "inline" not working.

### ISSUE THREAD

**Issue by shahreyar-abeer** [Appsilon/shiny.semantic#344]
Hi,

Please see below the attached screenshot.
The checkbox is not 'inline' as its supposed to be.

![image](https://user-images.githubusercontent.com/20732893/103867786-23ed6400-50f2-11eb-8e95-dc5283096df6.png)

**Comment by dokato** [comment]
Thank you @shahreyar-abeer for reporting this, we will have a look.

**Comment by ncullen93** [comment]
you can try wrapping it in a div with class="ui form" as follows:

```R
  div(class="ui form",
    multiple_checkbox("checkboxes", "Select Letters", LETTERS[1:6], value = "A", position='inline')
  )
```

**Comment by dokato** [comment]
#356 should fix that feel free to reopen

**Comment by brianmsm** [comment]
Hi
I have the last version from github, but the issue persists. The @ncullen93 's solution works fine. I would also like to point out another point. The `multiple_checkbox` function has its `multiple_radio` variant, which is differentiated by the argument `type = "radio"`. However, the function `checkbox_input` does not have a variant `radio_input`, and although putting as argument `type = "radio"`, it works fine, this is not documented.
